trigger: none

pool: Default

variables:
- group: infracost-secrets

stages:
  - stage: terraforminitValidationPlan
    displayName: terraform init, validate and plan
    jobs:
      - job: initValidatePlan
        displayName: Init, Validate and Plan
        steps:
        - task: TerraformTask@5
          displayName: terraform init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
            backendServiceArm: 'InfraServiceConnection'
            backendAzureRmStorageAccountName: 'rackteckstg'
            backendAzureRmContainerName: 'rackteckcont'
            backendAzureRmKey: 'dev.tfstate'

  - stage: securityScanning
    displayName: securityScanning
    jobs:
      - job: tflint
        steps:
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: |
              tflint --init
              tflint
            workingDirectory: '$(system.DefaultWorkingDirectory)'

      - job: tfsec
        steps:
        - task: tfsec@1
          inputs:
            version: 'v1.26.0'
            dir: '$(system.DefaultWorkingDirectory)'

      - job: checkov
        displayName: checkovscanning
        steps:
        - task: PowerShell@2
          displayName: checkov
          continueOnError: true
          inputs:
            targetType: 'inline'
            script: 'checkov -d $(system.defaultworkingdirectory) -o junitxml > checkov.out.xml'
            workingDirectory: '$(system.DefaultWorkingDirectory)'

        - task: PublishTestResults@2
          inputs:
            testResultsFormat: 'JUnit'
            testResultsFiles: 'checkov.out.xml'

  - stage: TerraformPlan
    displayName: TerraformPlan
    jobs:
      - job: TerraformPlan
        displayName: TerraformPlan
        steps:
        - task: TerraformTask@5
          displayName: terraform init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
            backendAzureRmUseEntraIdForAuthentication: false
            backendServiceArm: 'InfraServiceConnection'
            backendAzureRmStorageAccountName: 'rackteckstg'
            backendAzureRmContainerName: 'rackteckcont'
            backendAzureRmKey: 'dev.tfstate'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
            environmentServiceNameAzureRM: 'InfraServiceConnection'

  - stage: ManualValidation
    displayName: ManualValidation
    pool: server
    jobs:
      - job: ManualValidation
        displayName: ManualValidation
        steps:
        - task: ManualValidation@1
          inputs:
            notifyUsers: 'Yogesh Singh'
            instructions: 'For your approval.'



  - stage: infrocostcheck
    displayName: infracost check
    jobs:
      - job: infracostcheck
        displayName: infracost check
        steps:
        - task: TerraformTask@5
          displayName: terraform init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
            backendAzureRmUseEntraIdForAuthentication: false
            backendServiceArm: 'InfraServiceConnection'
            backendAzureRmStorageAccountName: 'rackteckstg'
            backendAzureRmContainerName: 'rackteckcont'
            backendAzureRmKey: 'dev.tfstate'

        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: 'infracost breakdown --path=$(System.DefaultWorkingDirectory)/env/dev --format=json --out-file=$(Build.ArtifactStagingDirectory)/infracost.json'
          env:
            INFRACOST_API_KEY: $(INFRACOST_API_KEY)


  - stage: terraformApply
    displayName: terraformApply
    jobs:
      - job: terraformApply
        displayName: terraformApply
        steps:
        - task: TerraformTask@5
          displayName: terraform init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
            backendAzureRmUseEntraIdForAuthentication: false
            backendServiceArm: 'InfraServiceConnection'
            backendAzureRmStorageAccountName: 'rackteckstg'
            backendAzureRmContainerName: 'rackteckcont'
            backendAzureRmKey: 'dev.tfstate'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
            environmentServiceNameAzureRM: 'InfraServiceConnection'

