name: application demo workflow

on: workflow_dispatch

jobs:
  demo:
    name: demo jobs
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: greetings
        run: echo "Hello World"

      - name: list files
        run: ls -l
      
